=== agascas2409/Lenguaje-de-Marcas/Tema 4/ejercicios/ejercicio4.3/en1archivo/assets/ejercicio4.3.dtd
<!ELEMENT restaurante (menu,recetas,clientes)>

<!ELEMENT menu (platoM+)>
<!ELEMENT platoM (nombreM,categoria,ingredientesM,precio)>
<!ELEMENT nombreM (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT ingredientesM (ingredienteM+)>
<!ELEMENT ingredienteM (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda (USD|EUR|GBP) #REQUIRED>

<!ELEMENT recetas (receta+)>
<!ELEMENT receta (nombreR,ingredientesR,preparacion)>
<!ELEMENT nombreR (#PCDATA)>
<!ELEMENT ingredientesR (ingredienteR+)>
<!ELEMENT ingredienteR (nombre-ingrediente)>
<!ELEMENT nombre-ingrediente (#PCDATA)>
<!ELEMENT preparacion (paso+)>
<!ELEMENT paso (#PCDATA)>
<!ATTLIST receta comensal (adultos|niÃ±os) #REQUIRED>
<!ATTLIST ingredienteR cantidad CDATA #REQUIRED>

<!ELEMENT clientes (cliente+)>
<!ELEMENT cliente (nombreC,telefono,correo,pedidos)>
<!ELEMENT nombreC (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT pedidos (pedido+)>
<!ELEMENT pedido (fecha,platoC+)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT platoC (#PCDATA)>

=== agascas2409/Lenguaje-de-Marcas/Tema 4/ejercicios/ejercicio4.3/en1archivo/ejercicio4.3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE restaurante SYSTEM "assets/ejercicio4.3.dtd">
<restaurante>
    <menu>
        <platoM>
            <nombreM></nombreM>
            <categoria></categoria>
            <ingredientesM>
                <ingredienteM></ingredienteM>
            </ingredientesM>
            <precio moneda="USD"></precio>
        </platoM>
    </menu>
    <recetas>
        <receta comensal="adultos">
            <nombreR></nombreR>
            <ingredientesR>
                <ingredienteR cantidad="0">
                    <nombre-ingrediente></nombre-ingrediente>
                </ingredienteR>
            </ingredientesR>
            <preparacion>
                <paso></paso>
            </preparacion>
        </receta>
    </recetas>
    <clientes>
        <cliente>
            <nombreC></nombreC>
            <telefono></telefono>
            <correo></correo>
            <pedidos>
                <pedido>
                    <fecha></fecha>
                    <platoC></platoC>
                </pedido>
            </pedidos>
        </cliente>
    </clientes>
</restaurante>
