=== agascas2409/Lenguaje-de-Marcas/Tema 4/ejercicios/ejercicio4.3/enVariosArchivos/assets/ejercicio3.dtd
<!ELEMENT clientes (cliente+)>
<!ELEMENT cliente (nombre,telefono,correo,pedidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT pedidos (pedido+)>
<!ELEMENT pedido (fecha,plato+)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT plato (#PCDATA)>

=== agascas2409/Lenguaje-de-Marcas/Tema 4/ejercicios/ejercicio4.3/enVariosArchivos/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clientes SYSTEM "assets/ejercicio3.dtd">
<clientes>
    <cliente>
        <nombre></nombre>
        <telefono></telefono>
        <correo></correo>
        <pedidos>
            <pedido>
                <fecha></fecha>
                <plato></plato>
            </pedido>
        </pedidos>
    </cliente>
</clientes>
