=== agascas2409/Lenguaje-de-Marcas/Tema 4/examen/examenXML/ejercicio1/reserva.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="respuestaConfirmada">
        <xs:restriction base="xs:string">
            <xs:enumeration value="si"></xs:enumeration>
            <xs:enumeration value="no"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoHabitacion">
        <xs:restriction base="xs:string">
            <xs:enumeration value="individual"></xs:enumeration>
            <xs:enumeration value="doble"></xs:enumeration>
            <xs:enumeration value="suite"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="edadCliente">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="18"></xs:minInclusive>
            <xs:maxInclusive value="120"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="reservas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="reserva" minOccurs="1" maxOccurs="50">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cliente">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"></xs:element>
                                        <xs:element name="apellidos" type="xs:string"></xs:element>
                                        <xs:element name="edad" type="edadCliente"></xs:element>
                                        <xs:element name="direccion" type="xs:string"></xs:element>
                                        <xs:choice>
                                            <xs:element name="telefono" type="xs:string"></xs:element>
                                            <xs:element name="email" type="xs:string"></xs:element>
                                        </xs:choice>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="habitacion">
                                <xs:complexType mixed="true">
                                    <xs:attribute name="tipo" type="tipoHabitacion"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="confirmada" type="respuestaConfirmada"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== agascas2409/Lenguaje-de-Marcas/Tema 4/examen/examenXML/ejercicio1/reserva.xml
<?xml version="1.0" encoding="UTF-8"?>
<reservas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="reserva.xsd">
    <reserva confirmada="si">
        <cliente>
            <nombre>Juan</nombre>
            <apellidos>Pérez</apellidos>
            <edad>30</edad>
            <direccion>Calle Jalon 45</direccion>
            <telefono>123456789</telefono>
        </cliente>
        <habitacion tipo="doble">322</habitacion>
    </reserva>
    <reserva confirmada="no">
        <cliente>
            <nombre>Juan</nombre>
            <apellidos>Pérez</apellidos>
            <edad>30</edad>
            <direccion>Calle Jalon 45</direccion>
            <email>123456789</email>
        </cliente>
        <habitacion tipo="individual">322</habitacion>
    </reserva>
</reservas>
