=== agascas2409/Lenguaje-de-Marcas/Tema 4/ejercicios/ejercicio4.3/assets/ejercicio2.dtd
<!ELEMENT recetas (receta+)>
<!ELEMENT receta (nombre,ingredientes,preparacion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente (nombre-ingrediente)>
<!ELEMENT nombre-ingrediente (#PCDATA)>
<!ELEMENT preparacion (paso+)>
<!ELEMENT paso (#PCDATA)>
<!ATTLIST receta comensal (adultos|niÃ±os) #REQUIRED>
<!ATTLIST ingrediente cantidad CDATA #REQUIRED>

=== agascas2409/Lenguaje-de-Marcas/Tema 4/ejercicios/ejercicio4.3/enVariosArchivos/ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recetas SYSTEM "assets/ejercicio2.dtd">
<recetas>
    <receta comensal="adultos">
        <nombre></nombre>
        <ingredientes>
            <ingrediente cantidad="0">
                <nombre-ingrediente></nombre-ingrediente>
            </ingrediente>
        </ingredientes>
        <preparacion>
            <paso></paso>
        </preparacion>
    </receta>
</recetas>
