=== agascas2409/Lenguaje-de-Marcas/Tema 4/ejemplos/DTD_Externo.dtd
<!ELEMENT aviso (de, (para|cc)*,mensajes,direccion?)>
<!ELEMENT de (#PCDATA)>
<!ELEMENT para (#PCDATA)>
<!ELEMENT cc (#PCDATA)>
<!-- <!ELEMENT mensajes (mensaje+)> uno o mas -->
<!ELEMENT mensajes (mensaje+)>
<!ELEMENT mensaje (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!-- <!ATTLIST mensaje tipo ID #REQUIRED> -->
<!ATTLIST mensaje tipo (facebook|whatsapp|x) "facebook">

=== agascas2409/Lenguaje-de-Marcas/Tema 4/ejemplos/DTD_Externo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aviso SYSTEM "DTD_Externo.dtd">
<aviso>
    <de>David</de>
    <para>Rosalía</para>
    <cc>Pepe</cc>
    <mensajes>
        <mensaje tipo="facebook">Mañana nos vemos en el estudio a las 10.</mensaje>
        <mensaje tipo="x">Mañana nos vemos en el estudio</mensaje>
    </mensajes>
    <direccion>Esto es una direccion</direccion>
</aviso>
